#!/usr/bin/env bash

set -e

host=$(hostname)

dest_host="gibbs.uberspace.de"
dest_dir="${HOME}/html"

if [ "$host" != "$dest_host" ]; then
  dest="${dest_host}:${dest_dir}"
else
  dest=$dest_dir
fi

project_dir=$(git rev-parse --show-toplevel)
site_dir=${project_dir}"/_site"

cd ${project_dir}
bundle exec jekyll build

echo "-----------------------------------------"
echo " 🛠  Site successfully built with Jekyll "
echo "-----------------------------------------"

echo $dest

rsync --recursive --verbose ${site_dir}/* ${dest}

echo "-------------------------------------"
echo " 🏗  Exocortex successfully deployed "
echo "-------------------------------------"
