title: Exocortex
author: Moritz
email: moritz@anothernode.com
description: >- # this means to ignore newlines until "baseurl:"
  An exocortex is formed by "any mental memory or processing component that
  resides outside your physical brain." (Andy Hunt)
baseurl: ""
url: "https://exocortex.anothernode.com"
twitter_username: anothernode
github_username: anothernode

collections:
  non_nav_pages:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - meta
