title: Exocortex
author: Moritz
email: moritz@anothernode.com
description: >- # this means to ignore newlines until "baseurl:"
  »Who needs talent when you have intensity?« - Jeff Atwood
baseurl: ""
url: "https://exocortex.anothernode.com"
twitter_username: anothernode
github_username: moritzreiter

collections:
  non_nav_pages:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - meta
